#! /usr/bin/env perl
use warnings;
use strict;

# the rules, according to
# https://imranontech.com/2007/01/24/using-fizzbuzz-to-find-developers-who-grok-coding/
#     Write a program that prints the numbers from 1 to 100. But for multiples
#     of three print “Fizz” instead of the number and for the multiples of
#     five print “Buzz”. For numbers which are multiples of both three and
#     five print “FizzBuzz”.

my $max = 100;

if (int rand 2) {
    for my $n (1 .. $max) {
        if ($n % 3 == 0) {
            print "fizz"
        }
        if ($n % 5 == 0) {
            print "buzz"
        }
        if ($n % 3 && $n % 5) {
            print $n;
        }
        print "\n";
    }
} else {
    for (1 .. $max) {
        print "fizz" unless $_ % 3;
        print "buzz" unless $_ % 5;
        print if $_ % 3 && $_ % 5;
        print "\n";
    }
}
