#! /usr/bin/env perl
#perl -le'$x=eval shift;print int($x*=60)while$x-=int$x'

# this only converts the fractional part
# it ignores the integer part

use warnings;
use strict;

my $victim = eval shift;
my @digits;

while ($victim -= int $victim) {
    $victim *= 60;
    push @digits, int $victim;
}

print '0;', join(',', @digits), "\n";
