#! /usr/local/bin/perl
use warnings;
use strict;

use HTML::FormatRTF;

my $in_file = shift;
my $out_file = $in_file;  $out_file =~ s#^(?:[^/]*/)*([^/]*)\.html$#$1.rtf#;
warn $out_file;

open(RTF, ">$out_file")
    or die "Can't write-open $out_file: $!\nAborting";

print RTF HTML::FormatRTF->format_file(
        $in_file,
        'fontname_headings' => "Verdana",
);
close(RTF);
