#! /usr/local/bin/perl

use warnings;
use strict;

my $length = shift || 63;

no warnings qw( qw );
my @choices = qw(
    A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    a b c d e f g h i j k l m n o p q r s t u v w x y z
    0 1 2 3 4 5 6 7 8 9 - = ~ ! @ # $ % ^ & * ( ) _ +
    [ ] \ { } | ; ' : " , . / < > ?
);  # ` should be in there, too, but iPhone doesn't have a `

my $shared_key = '';
for (1 .. $length) {
    $shared_key .= $choices[ rand @choices ];
}

print "$shared_key\n";
